project_name: loophole

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - pkger
    
builds:
- id: loophole-cli
  binary: loophole
  goos:
    - linux
    - windows
  goarch:
    - 386
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
  flags:
  - -tags=skippkger

- id: loophole-cli-macos
  binary: loophole
  goos:
    - darwin
  goarch:
    - amd64
  goarm:
    - 6
    - 7
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}
  flags:
  - -tags=skippkger
  hooks:
    post: gon gon.hcl

- id: loophole-desktop-linux
  binary: loophole-desktop
  goos:
    - linux
  goarch:
    - amd64
    - 386
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X config.version={{.Version}} -X config.commit={{.Commit}}
  flags:
  - -tags=desktop

- id: loophole-desktop-macos
  binary: loophole-desktop
  goos:
    - darwin
  goarch:
    - amd64
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X config.version={{.Version}} -X config.commit={{.Commit}}
  flags:
  - -tags=desktop
  hooks:
    post: gon gon.hcl

- id: loophole-desktop-win
  binary: loophole-desktop
  goos:
    - windows
  goarch:
    - amd64
    - 386
  mod_timestamp: "{{ .CommitTimestamp }}"
  ldflags:
    - -s -w -X config.version={{.Version}} -X config.commit={{.Commit}} -H windowsgui
  flags:
  - -tags=desktop

archives:
  - id: cli
    builds:
      - loophole-cli
    replacements:
      amd64: 64bit
      386: 32bit
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}-cli_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
  - id: desktop
    builds:
      - loophole-desktop
      - loophole-desktop-win
    replacements:
      amd64: 64bit
      386: 32bit
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    wrap_in_directory: true
    name_template: "{{ .ProjectName }}-desktop_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - go mod tidy
