version: "3.6"

services:
  gateway:
    build: ./support/gateway
    ports:
      - "2222"

  proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./support/proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  loophole:
    image: kroniak/ssh-client
    volumes:
      - ./support/secrets/id_rsa:/root/.ssh/id_rsa:ro
      - ./support/secrets/config:/root/.ssh/config:ro
    command: "sh -c \"sleep 5 && ssh -4 -N -R *:8080:myservice:80 gateway\""

  myservice:
    image: nginx
