name: goreleaser build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: yarn
        working-directory: ./ui/desktop

      - run: yarn build
        working-directory: ./ui/desktop

      - name: Get pkger
        run: go get -u github.com/markbates/pkger/cmd/pkger

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --snapshot --skip-publish --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: binaries
          path: |
            dist/*.tgz
            dist/*.tar.gz
            dist/*.zip
