name: goreleaser release

on: 
  release:
    types: [created]

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      - run: npm install
        working-directory: ./internal/app/metrics/static/dashboard
      - run: npm run build
        working-directory: ./internal/app/metrics/static/dashboard

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}