name: goreleaser release

on:
  release:
    types: [created]

jobs:
  goreleaser:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: yarn
        working-directory: ./ui/desktop

      - run: yarn build
        working-directory: ./ui/desktop

      - name: Get pkger
        run: go get -u github.com/markbates/pkger/cmd/pkger

      - name: Import Apple Signing Certificate
        uses: apple-actions/import-codesign-certs@v1
        with: 
          p12-file-base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
